### ISSUE TITLE
Pull Request?

### ISSUE THREAD

**Issue by raphaelluchini** [imgntn/samsung-smartTV-packager#4]
Hello @imgntn , I'm developing some samsung apps and your code was really useful! I made some refactors in the code and I've published to npm as well.

What do you think I create a pull request for those new changes? I mean, there's lots of changes.

Thanks!

**Comment by imgntn** [comment]
@raphaelluchini -- definitely!  glad it's been useful -- happy to take your PR and also to add you as a collaborator / transfer ownership if you're interested in maintaining.  i'm actually not working on samsung apps at the moment.  let me know!

**Comment by imgntn** [comment]
Made a PR from your fork & added -- thanks!
